### ISSUE TITLE
How can collect static on the installed_apps for dependency apps static files or admin pages?

### ISSUE THREAD

**Issue by gokhyildiz** [khadegd/django-webpack-starter#11]
Hello, i used the starter kit structure you created. When I wanted to work with this blueprint, I could not find how the deployment process should be set up. I have set "/assets/bundles" as static files myself, but I could not find how to collect dependencies of other installed_apps applications or admin panel dependencies. Thanks.

**Comment by khadegd** [comment]
Set a `STATIC_ROOT`, then run a `python manage.py collectstatic`.

Excerpt from - https://github.com/jazzband/django-webpack-loader#how-to-use-in-production

## How to use in Production

**It is up to you**. There are a few ways to handle this. I like to have slightly separate configs for production and local. I tell git to ignore my local stats + bundle file but track the ones for production. Before pushing out newer version to production, I generate a new bundle using production config and commit the new stats file and bundle. I store the stats file and bundles in a directory that is added to the `STATICFILES_DIR`. This gives me integration with collectstatic for free. The generated bundles are automatically collected to the target directory and synched to S3.


`./webpack_production.config.js`
```javascript
var config = require('./webpack.config.js');
var BundleTracker = require('webpack-bundle-tracker');

config.output.path = require('path').resolve('./assets/dist');

config.plugins = [
    new BundleTracker({filename: './webpack-stats-prod.json'})
]

// override any other settings here like using Uglify or other things that make sense for production environments.

module.exports = config;
```

`settings.py`
```python
if not DEBUG:
    WEBPACK_LOADER.update({
        'BUNDLE_DIR_NAME': 'dist/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats-prod.json')
    })
```

<br><br>


You can also simply generate the bundles on the server before running collectstatic if that works for you.
